# yaml-language-server: $schema=
# golangci-lint v1 format (v2 not yet released)

run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  dupl:
    threshold: 200
  gocyclo:
    min-complexity: 60
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - rangeValCopy
      - octalLiteral
      - unnamedResult
      - filepathJoin
  goimports:
    local-prefixes: github.com/signalridge/clinvoker
  misspell:
    locale: US
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - errcheck
    - path: vendor/
      linters:
        - all
    # Allow unchecked error returns for common patterns
    - linters:
        - errcheck
      text: "Error return value of .*(BindEnv|SetContent|WriteEvent|ParseLine).*"
    - linters:
        - errcheck
      text: "Error return value of .*(Signal|Copy|Init|Scanln|Sscanf).*"
    # Allow stuttering type names for clarity
    - linters:
        - revive
      text: "stutters"
    # Allow missing exhaustive switch cases for default modes and event types
    - linters:
        - exhaustive
      text: "missing cases.*(Default|EventInit|EventProgress|EventTokenUsage)"
    # Allow goconst for backend names and common strings
    - linters:
        - goconst
      text: "string .*(claude|codex|gemini|error|message|fast|best|balanced|FAILED|default|powerful|quick).*"
    # Allow duplicate code in backend implementations (intentionally similar structure)
    - path: internal/backend/(codex|gemini)\.go
      linters:
        - dupl
    # Allow staticcheck empty branches for error handling patterns
    - linters:
        - staticcheck
      text: "SA9003|SA5011"
    # Allow G306 for session files that need to be readable
    - linters:
        - gosec
      text: "G306"
