# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v2.jsonschema.json
# golangci-lint v2 format
version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    gocyclo:
      min-complexity: 60
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - rangeValCopy
        - octalLiteral
        - unnamedResult
        - filepathJoin
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
          - errcheck
      - path: vendor/
        linters:
          - all
      # Allow unchecked error returns for common patterns
      - linters:
          - errcheck
        text: "Error return value of .*(BindEnv|SetContent|WriteEvent|ParseLine).*"
      - linters:
          - errcheck
        text: "Error return value of .*(Signal|Copy|Init|Scanln|Sscanf).*"
      # Allow stuttering type names for clarity
      - linters:
          - revive
        text: "stutters"
      # Allow missing exhaustive switch cases for default modes and event types
      - linters:
          - exhaustive
        text: "missing cases.*(Default|EventInit|EventProgress|EventTokenUsage)"
      # Allow goconst for backend names and common strings
      - linters:
          - goconst
        text: "string .*(claude|codex|gemini|error|message|fast|best|balanced|FAILED|default|powerful|quick).*"
      # Allow duplicate code in backend implementations (intentionally similar structure)
      - path: internal/backend/(codex|gemini)\.go
        linters:
          - dupl
      # Allow staticcheck empty branches for error handling patterns
      - linters:
          - staticcheck
        text: "SA9003|SA5011"
      # Allow G306 for session files that need to be readable
      - linters:
          - gosec
        text: "G306"
      # Allow G204 for backend command execution with variables
      - linters:
          - gosec
        text: "G204"
      # Allow G304 for file reading with variable paths (config, session)
      - linters:
          - gosec
        text: "G304"
      # Allow G104 for BindEnv which returns error that's intentionally ignored
      - linters:
          - gosec
        text: "G104"
      # Allow noctx in test files, test utilities, and backend implementation
      - path: _test\.go
        linters:
          - noctx
      - path: internal/mock/
        linters:
          - noctx
      - path: internal/backend/
        linters:
          - noctx
      # Allow staticcheck style suggestions (QF series)
      - linters:
          - staticcheck
        text: "QF1001|QF1003"
      # Allow errors package naming conflict
      - path: internal/errors/
        linters:
          - revive
        text: "var-naming.*avoid package names"
      # Allow missing comment for SessionStatus consts
      - path: internal/session/session\.go
        linters:
          - revive
        text: "exported.*should have comment"
      # Allow util package name (common Go convention)
      - path: internal/util/
        linters:
          - revive
        text: "avoid meaningless package names"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/signalridge/clinvoker
