# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: clinvoker
before:
  hooks:
    - go mod tidy
builds:
  - id: clinvk
    main: ./cmd/clinvk
    binary: clinvk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/signalridge/clinvoker/internal/app.version={{.Version}}
      - -X github.com/signalridge/clinvoker/internal/app.commit={{.ShortCommit}}
      - -X github.com/signalridge/clinvoker/internal/app.date={{.Date}}
archives:
  - id: clinvk
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
release:
  github:
    owner: signalridge
    name: clinvoker
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
brews:
  - name: clinvk
    repository:
      owner: signalridge
      name: homebrew-tap
    homepage: "https://github.com/signalridge/clinvoker"
    description: "Unified AI CLI wrapper for multiple backends"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "clinvk"
    test: |
      system "#{bin}/clinvk", "--version"
scoops:
  - name: clinvk
    repository:
      owner: signalridge
      name: scoop-bucket
    homepage: "https://github.com/signalridge/clinvoker"
    description: "Unified AI CLI wrapper for multiple backends"
    license: MIT
    skip_upload: auto
nfpms:
  - id: clinvk
    package_name: clinvk
    vendor: SignalRidge
    homepage: "https://github.com/signalridge/clinvoker"
    maintainer: "SignalRidge <support@signalridge.com>"
    description: "Unified AI CLI wrapper for multiple backends"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    priority: optional
aurs:
  - name: clinvk-bin
    homepage: "https://github.com/signalridge/clinvoker"
    description: "Unified AI CLI wrapper for multiple backends"
    maintainers:
      - "SignalRidge <support@signalridge.com>"
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/clinvk-bin.git"
    skip_upload: auto
    package: |-
      install -Dm755 "./clinvk" "${pkgdir}/usr/bin/clinvk"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clinvk/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/clinvk/README.md"
# Docker images
dockers:
  - id: clinvk-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .ShortCommit }}"
      - "--build-arg=DATE={{ .Date }}"
  - id: clinvk-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .ShortCommit }}"
      - "--build-arg=DATE={{ .Date }}"
# Multi-arch manifest
docker_manifests:
  - name_template: "ghcr.io/signalridge/clinvk:{{ .Version }}"
    image_templates:
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-amd64"
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-arm64"
  - name_template: "ghcr.io/signalridge/clinvk:latest"
    image_templates:
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-amd64"
      - "ghcr.io/signalridge/clinvk:{{ .Version }}-arm64"
# SBOM generation
sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.spdx.json"
# Sign artifacts with cosign
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true
# Sign container images
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: manifests
    output: true
    args:
      - sign
      - "${artifact}@${digest}"
      - "--yes"
