name: Lint Markdown
on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - '!CHANGELOG.md'
      - '.markdownlint.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'
      - '!CHANGELOG.md'
      - '.markdownlint.yaml'
permissions:
  contents: read
jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          config: .markdownlint.yaml
          globs: |
            **/*.md
            !CHANGELOG.md
